version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: loan-predict-backend:latest
    container_name: loan-predict-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: loan-predict-frontend:latest
    container_name: loan-predict-frontend
    ports:
      - "3000:3000" #Correct port mapping for Next.js
    depends_on:
      - backend
    restart: unless-stopped