apiVersion: v1
kind: Service
metadata:
  name: loan-predict-frontend-service
  namespace: default # Or your frontend deployment's namespace
spec:
  type: NodePort
  selector:
    app: loan-predict-frontend
  ports:
    - protocol: TCP
      port: 3000 # The port you want to expose externally
      targetPort: 3000 # The port your frontend container listens on